import type { CharacterDef, CharacterId } from '@/types'

/**
 * The four playable characters. Differences are strictly cosmetic
 * (hair, eyes, build, outfit) — no gameplay advantages, per the design pillar.
 */
export const CHARACTERS: Record<CharacterId, CharacterDef> = {
  robin: {
    id: 'robin',
    name: 'Robin',
    description: 'Blonde bob · white tee',
    skin: '#e8b98f',
    hair: '#e6c26e',
    hairStyle: 'bob',
    eyes: '#5b3a21',
    shirt: '#f2f4f8',
    pants: '#27314a',
    shoes: '#cf3a57',
    height: 0.98,
    width: 0.92,
  },
  leif: {
    id: 'leif',
    name: 'Leif',
    description: 'Messy brown hair · blue eyes · black tee',
    skin: '#e2a87d',
    hair: '#5a3a22',
    hairStyle: 'messy',
    eyes: '#3a6ea5',
    shirt: '#1a1c22',
    pants: '#3a4254',
    shoes: '#e8e8e8',
    height: 1.0,
    width: 1.02,
  },
  jovan: {
    id: 'jovan',
    name: 'Jovan',
    description: 'Tall · short brown hair · white tee',
    skin: '#c98a5e',
    hair: '#4a3120',
    hairStyle: 'short',
    eyes: '#4a3120',
    shirt: '#f2f4f8',
    pants: '#222730',
    shoes: '#2b3a8c',
    height: 1.2,
    width: 0.95,
  },
  leo: {
    id: 'leo',
    name: 'Leo',
    description: 'Muscular · buzz cut · black tee',
    skin: '#d39468',
    hair: '#3c2a1a',
    hairStyle: 'buzz',
    eyes: '#3c2a1a',
    shirt: '#1a1c22',
    pants: '#2a2d36',
    shoes: '#e2932a',
    height: 1.03,
    width: 1.24,
  },
  till: {
    id: 'till',
    name: 'Till',
    description: 'Blonde · blue eyes · green tee',
    skin: '#ecbf95',
    hair: '#e8c660',
    hairStyle: 'side',
    eyes: '#3a6ea5',
    shirt: '#3f9d57',
    pants: '#2c3550',
    shoes: '#d9d9d9',
    height: 1.02,
    width: 0.98,
  },
  tusya: {
    id: 'tusya',
    name: 'Tusya',
    description: 'Brown skin · black hair · brown eyes',
    skin: '#8a5a3a',
    hair: '#15110f',
    hairStyle: 'long',
    eyes: '#3b2316',
    shirt: '#c9447a',
    pants: '#2a2d3a',
    shoes: '#f0e9e0',
    height: 0.99,
    width: 0.9,
  },
  lennard: {
    id: 'lennard',
    name: 'Lennard',
    description: 'Brown hair · brown eyes · glasses',
    skin: '#e0a87c',
    hair: '#5a3a22',
    hairStyle: 'short',
    eyes: '#4a3120',
    shirt: '#6c5ce7',
    pants: '#33384a',
    shoes: '#cfcfcf',
    height: 1.0,
    width: 1.0,
    glasses: true,
  },
  erim: {
    id: 'erim',
    name: 'Erim',
    description: 'Black hair · brown eyes · beard',
    skin: '#caa074',
    hair: '#15110f',
    hairStyle: 'short',
    eyes: '#3b2316',
    shirt: '#2f3b4c',
    pants: '#23262f',
    shoes: '#9aa0ad',
    height: 1.05,
    width: 1.1,
    beard: true,
  },
  david: {
    id: 'david',
    name: 'David',
    description: 'Brown hair · brown eyes · blue shirt',
    skin: '#dca27a',
    hair: '#4a3120',
    hairStyle: 'short',
    eyes: '#4a3120',
    shirt: '#2f6fd6',
    pants: '#2a2d36',
    shoes: '#e8e8e8',
    height: 1.04,
    width: 1.04,
  },
  sofia: {
    id: 'sofia',
    name: 'Sofia',
    description: 'Moroccan · long blonde hair',
    skin: '#bd8350',
    hair: '#e3c069',
    hairStyle: 'long',
    eyes: '#4a3120',
    shirt: '#1fa89a',
    pants: '#2c3142',
    shoes: '#f0e9e0',
    height: 0.97,
    width: 0.86,
  },
}

export const CHARACTER_ORDER: CharacterId[] = [
  'robin',
  'leif',
  'jovan',
  'leo',
  'till',
  'tusya',
  'lennard',
  'erim',
  'david',
  'sofia',
]
